version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: redis-service
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - backend-net
    restart: unless-stopped

  discord-bot:
    build:
      context: ./jawn  
      dockerfile: Dockerfile
    container_name: discord-bot
    environment:
      - REDIS_HOST=redis-service 
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - POST_VERIFIED_ROLE_ID=${POST_VERIFIED_ROLE_ID}
      - WEB_HOST=${WEB_HOST}
      - BOT_LOGS_CHANNEL_ID=${BOT_LOGS_CHANNEL_ID}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    depends_on:
      - redis
    networks:
      - backend-net
    restart: unless-stopped

  astro-server:
    build:
      context: ./web 
    container_name: astro-server
    ports:
      - "80:4321"
    environment:
      - REDIS_HOST=redis-service
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - DEV=false
    depends_on:
      - redis
    networks:
      - backend-net
    restart: unless-stopped

networks:
  backend-net:
    driver: bridge