version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: redis-service
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - backend-net
    restart: unless-stopped

  discord-bot:
    build:
      context: ./jawn  
      dockerfile: Dockerfile
    container_name: discord-bot
    environment:
      - REDIS_HOST=redis-service 
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - POST_VERIFIED_ROLE_ID=${POST_VERIFIED_ROLE_ID}
      - VERIFICATION_LOGS_CHANNEL=${VERIFICATION_LOGS_CHANNEL}
      - WEB_HOST=${WEB_HOST}
      - BOT_LOGS_CHANNEL_ID=${BOT_LOGS_CHANNEL_ID}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - JAVA_OPTS=-XX:+UseG1GC -XX:+ExitOnOutOfMemoryError -DVERIFICATION_LOGS_CHANNEL=${VERIFICATION_LOGS_CHANNEL}
    depends_on:
      - redis
    networks:
      - backend-net
    restart: unless-stopped

  astro-server:
    build:
      context: ./web 
    container_name: astro-server
    environment:
      - REDIS_HOST=redis-service
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - DEV=false
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - WEB_HOST=${WEB_HOST}
      
    depends_on:
      - redis
    networks:
      - backend-net
    restart: unless-stopped

  reverse-proxy:
    image: caddy:2-alpine
    container_name: reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    command: caddy reverse-proxy --from jawn.jauster.xyz --to astro-server:4321
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - backend-net
    restart: unless-stopped

networks:
  backend-net:
    driver: bridge

volumes:
  caddy_data:
  caddy_config: